language: node_js
node_js:
  - "0.10"
env:
  global:
    # Sauce Labs are OK with this and it is currently necessary to expose this information for testing pull requests;
    # please get your own free key if you want to test yourself
    - SAUCE_USERNAME: revolverjs
    - SAUCE_ACCESS_KEY: c0408be0-b8ea-4245-b2de-29ccb698c7d8
# This extra install section is only necessary if your project has already installed AMD dependencies like Dojo using
# npm, since AMD path resolution does not follow Node.js path resolution rules but npm does not know this
install:
  - npm install
  - cd node_modules/intern
  - npm install --production
  - cd ../..
script: node node_modules/intern/runner.js config=tests/intern